corpusDir: './corpus-sanity/'
testMode: assertion
coverage: true
solcArgs: "--evm-version cancun --optimize-runs 200"
testLimit: 10000  # Lower limit since we expect failures quickly
shrinkLimit: 5000
propMaxGas: 0xffffffffffffffff
testMaxGas: 0xffffffffffffffff
codeSize: 0x60000000